-- ==========================================
-- 1. Create channel_proposals Table
-- ==========================================
CREATE TABLE IF NOT EXISTS public.channel_proposals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  name text NOT NULL,
  type text NOT NULL,
  image_url text,
  links jsonb,
  status text DEFAULT 'pending' NOT NULL CHECK (status IN ('pending', 'approved', 'rejected')),
  approved_channel_id bigint REFERENCES public.channels(id) ON DELETE SET NULL
);

-- Enable RLS on channel_proposals
ALTER TABLE public.channel_proposals ENABLE ROW LEVEL SECURITY;

-- Select policy: Owner or Admin
CREATE POLICY "Enable select for owner or admin on channel_proposals" ON public.channel_proposals
  FOR SELECT USING (
    auth.uid() = user_id OR 
    EXISTS (
      SELECT 1 FROM public.profiles 
      WHERE id = auth.uid() AND is_admin = true
    )
  );

-- Insert policy: Authenticated users
CREATE POLICY "Enable insert for authenticated users on channel_proposals" ON public.channel_proposals
  FOR INSERT WITH CHECK (auth.uid() IS NOT NULL AND auth.uid() = user_id);

-- Update policy: Admin only
CREATE POLICY "Enable update for admins on channel_proposals" ON public.channel_proposals
  FOR UPDATE USING (
    EXISTS (
      SELECT 1 FROM public.profiles 
      WHERE id = auth.uid() AND is_admin = true
    )
  );

-- Delete policy: Admin only
CREATE POLICY "Enable delete for admins on channel_proposals" ON public.channel_proposals
  FOR DELETE USING (
    EXISTS (
      SELECT 1 FROM public.profiles 
      WHERE id = auth.uid() AND is_admin = true
    )
  );


-- ==========================================
-- 2. Create event_proposals Table
-- ==========================================
CREATE TABLE IF NOT EXISTS public.event_proposals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  status text DEFAULT 'pending' NOT NULL CHECK (status IN ('pending', 'approved', 'rejected')),
  
  -- Common Fields
  is_offline boolean NOT NULL,
  is_online boolean NOT NULL,
  title text NOT NULL,
  description text,
  image_url text,
  links jsonb,
  
  -- Offline Specific Fields
  start_date date,
  end_date date,
  start_time time without time zone,
  end_time time without time zone,
  reservation_type text,
  is_reservation_always boolean DEFAULT false,
  reservation_starts_at timestamp with time zone,
  reservation_ends_at timestamp with time zone,
  locations jsonb,
  schedules jsonb,
  support_images jsonb,
  
  -- Online Specific Fields
  online_start_at timestamp with time zone,
  online_end_at timestamp with time zone,
  
  -- Mapping / Relation tracking
  channel_ids jsonb,
  channel_proposal_id bigint REFERENCES public.channel_proposals(id) ON DELETE SET NULL,
  approved_event_id bigint REFERENCES public.events(id) ON DELETE SET NULL
);

-- Enable RLS on event_proposals
ALTER TABLE public.event_proposals ENABLE ROW LEVEL SECURITY;

-- Select policy: Owner or Admin
CREATE POLICY "Enable select for owner or admin on event_proposals" ON public.event_proposals
  FOR SELECT USING (
    auth.uid() = user_id OR 
    EXISTS (
      SELECT 1 FROM public.profiles 
      WHERE id = auth.uid() AND is_admin = true
    )
  );

-- Insert policy: Authenticated users
CREATE POLICY "Enable insert for authenticated users on event_proposals" ON public.event_proposals
  FOR INSERT WITH CHECK (auth.uid() IS NOT NULL AND auth.uid() = user_id);

-- Update policy: Admin only
CREATE POLICY "Enable update for admins on event_proposals" ON public.event_proposals
  FOR UPDATE USING (
    EXISTS (
      SELECT 1 FROM public.profiles 
      WHERE id = auth.uid() AND is_admin = true
    )
  );

-- Delete policy: Admin only
CREATE POLICY "Enable delete for admins on event_proposals" ON public.event_proposals
  FOR DELETE USING (
    EXISTS (
      SELECT 1 FROM public.profiles 
      WHERE id = auth.uid() AND is_admin = true
    )
  );


-- ==========================================
-- 3. Trigger: Auto-reject event proposals on channel rejection
-- ==========================================
CREATE OR REPLACE FUNCTION public.handle_channel_proposal_rejection()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.status = 'rejected' AND OLD.status = 'pending' THEN
    UPDATE public.event_proposals
    SET status = 'rejected'
    WHERE channel_proposal_id = NEW.id AND status = 'pending';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER trg_channel_proposal_rejection
  AFTER UPDATE ON public.channel_proposals
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_channel_proposal_rejection();


-- ==========================================
-- 4. Trigger: Pre-approval check (Enforce channel approval first)
-- ==========================================
CREATE OR REPLACE FUNCTION public.check_event_proposal_approval()
RETURNS TRIGGER AS $$
DECLARE
  v_channel_status text;
BEGIN
  IF NEW.status = 'approved' AND (OLD.status IS NULL OR OLD.status <> 'approved') THEN
    IF NEW.channel_proposal_id IS NOT NULL THEN
      SELECT status INTO v_channel_status
      FROM public.channel_proposals
      WHERE id = NEW.channel_proposal_id;
      
      IF v_channel_status IS NULL OR v_channel_status <> 'approved' THEN
        RAISE EXCEPTION '연결된 채널 제안이 아직 승인되지 않았습니다. 채널 승인이 완료된 후 행사를 승인할 수 있습니다.';
      END IF;
    END IF;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER trg_check_event_proposal_approval
  BEFORE UPDATE ON public.event_proposals
  FOR EACH ROW
  EXECUTE FUNCTION public.check_event_proposal_approval();
